# Generated by Django 5.1.4 on 2024-12-20 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Load',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(blank=True, max_length=200, null=True)),
                ('reference_id', models.CharField(blank=True, max_length=200, null=True)),
                ('instructions', models.CharField(blank=True, max_length=200, null=True)),
                ('bills', models.IntegerField(blank=True, null=True)),
                ('created_by', models.CharField(blank=True, max_length=200, null=True)),
                ('created_date', models.CharField(blank=True, max_length=200, null=True)),
                ('load_id', models.CharField(blank=True, max_length=200, null=True)),
                ('trip_id', models.IntegerField(blank=True, null=True)),
                ('customer_broker', models.CharField(blank=True, max_length=200, null=True)),
                ('driver', models.CharField(blank=True, max_length=200, null=True)),
                ('co_driver', models.CharField(blank=True, max_length=100, null=True)),
                ('truck', models.CharField(blank=True, max_length=200, null=True)),
                ('dispatcher', models.CharField(blank=True, max_length=200, null=True)),
                ('load_status', models.CharField(blank=True, choices=[('OFFER', 'Offer'), ('BOOKED', 'Booked'), ('DISPATCHED', 'Dispatched'), ('INTRANSIT', 'Intransit'), ('DELIVERED', 'Delivered'), ('INVOICED', 'Invoiced'), ('PAID', 'Paid')], max_length=50, null=True)),
                ('tags', models.CharField(blank=True, max_length=200, null=True)),
                ('equipment_type', models.CharField(blank=True, choices=[('DRYVAN', 'Dryvan'), ('REEFER', 'Reefer'), ('CARHAUL', 'Carhaul'), ('FLATBED', 'Flatbed'), ('STEPDECK', 'Stepdeck'), ('POWERONLY', 'PowerOnly'), ('RGN', 'Rgn'), ('TANKERSTYLE', 'TankerStyle')], max_length=50, null=True)),
                ('trip_status', models.CharField(blank=True, max_length=50, null=True)),
                ('invoice_status', models.CharField(blank=True, max_length=50, null=True)),
                ('trip_bil_status', models.CharField(blank=True, max_length=50, null=True)),
                ('load_pay', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('driver_pay', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_pay', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('per_mile', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('mile', models.IntegerField(blank=True, null=True)),
                ('empty_mile', models.IntegerField(blank=True, null=True)),
                ('total_miles', models.IntegerField(blank=True, null=True)),
                ('flagged', models.BooleanField(blank=True, default=False, null=True)),
                ('flagged_reason', models.CharField(blank=True, max_length=100, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('chat', models.TextField(blank=True, null=True)),
                ('ai', models.BooleanField(blank=True, null=True)),
                ('rate_con', models.FileField(blank=True, null=True, upload_to='')),
                ('bol', models.FileField(blank=True, null=True, upload_to='')),
                ('pod', models.FileField(blank=True, null=True, upload_to='')),
                ('document', models.FileField(blank=True, null=True, upload_to='')),
                ('comercial_invoice', models.FileField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
