# Generated by Django 5.1.4 on 2025-01-03 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps_load', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='load',
            name='load_status',
            field=models.CharField(choices=[('OPEN', 'Open'), ('COVERED', 'Covered'), ('DISPATCHED', 'Dispatched'), ('LOADING', 'Loading'), ('ON ROUTE', 'On Route'), ('UNLOADING', 'Unloading'), ('IN YARD', 'In Yard'), ('DELIVERED', 'Delivered'), ('COMPLETED', 'Completed')], default='OPEN', max_length=100),
        ),
    ]
