# Generated by Django 5.1.4 on 2025-01-09 12:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps_load', '0003_customerbroker_dispatchertags_drivertags_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='load',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='dispatcher', to='apps_load.dispatcher'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='load',
            name='customer_broker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_broker', to='apps_load.customerbroker'),
        ),
        migrations.AlterField(
            model_name='load',
            name='dispatcher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_by', to='apps_load.dispatcher'),
        ),
        migrations.AlterField(
            model_name='load',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='driver', to='apps_load.driver'),
        ),
        migrations.AlterField(
            model_name='load',
            name='load_status',
            field=models.CharField(blank=True, choices=[('OPEN', 'Open'), ('COVERED', 'Covered'), ('DISPATCHED', 'Dispatched'), ('LOADING', 'Loading'), ('ON ROUTE', 'On Route'), ('UNLOADING', 'Unloading'), ('IN YARD', 'In Yard'), ('DELIVERED', 'Delivered'), ('COMPLETED', 'Completed')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='load',
            name='tags',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='loadtags', to='apps_load.loadtags'),
        ),
        migrations.AlterField(
            model_name='load',
            name='truck',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='truck', to='apps_load.truck'),
        ),
    ]
