# Generated by Django 5.1.4 on 2025-01-20 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps_load', '0004_alter_load_created_by_alter_load_customer_broker_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='load',
            name='message_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
