# Generated by Django 5.1.4 on 2024-12-18 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps_auth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_photo',
            field=models.ImageField(default='profile/profile_avatar.png', upload_to='profile'),
        ),
    ]
