# Generated by Django 5.1.4 on 2024-12-20 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps_auth', '0002_user_profile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_photo',
            field=models.ImageField(default='media/profile/profile_avatar.png', upload_to='media/profile'),
        ),
    ]
